export const Users = [
  {
    id: 1,
    name: "Janet Stephen",
    username: "janet_22",
    email: "amber@logan.tv",
    profilePicture: "/photos/persons/person-12.jpg",
  },
  {
    id: 2,
    name: "Jessica Randy",
    username: "Jessica_23",
    email: "isabella@randy.biz",
    profilePicture: "/photos/persons/person-3.jpg",
  },
  {
    id: 3,
    name: "James William",
    username: "James_24",
    email: "Sherwood@rosamond.me",
    profilePicture: "/photos/persons/person-4.jpg",
  },
  {
    id: 4,
    name: "Jennifer John",
    username: "Jennifer_25",
    email: "Chaim_McDermott@dana.io",
    profilePicture: "/photos/persons/person-5.jpg",
  },
  {
    id: 5,
    name: "Emily Jason",
    username: "Emily",
    email: "Rey.Padberg@karina.biz",
    profilePicture: "/photos/persons/person-15.jpg",
  },
  {
    id: 6,
    name: "Nicholas Ros",
    username: "Nicholas",
    email: "Nicholas Ros@karina.biz",
    profilePicture: "/photos/persons/person-6.jpg",
  },
  {
    id: 7,
    name: "Joseph Morgan",
    username: "Joseph",
    email: "Joseph@karina.biz",
    profilePicture: "/photos/persons/person-14.jpg",
  },
];

export const friendsOnline = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Gloria",
    email: "Sincere@april.biz",
    profilePicture: "/photos/persons/person-6.jpg",
    class: "onlineNow",
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Madison",
    email: "Shanna@melissa.tv",
    profilePicture: "/photos/persons/person-7.jpg",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Abigail",
    email: "Nathan@yesenia.net",
    profilePicture: "/photos/persons/person-8.jpg",
    class: "onlineNow",
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Sophia",
    email: "Julianne.OConner@kory.org",
    profilePicture: "/photos/persons/person-9.jpg",
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Marilyn",
    email: "Lucio_Hettinger@annie.ca",
    profilePicture:"/photos/persons/person-10.jpg",
    class: "onlineNow",
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Doris",
    email: "Karley_Dach@jasper.info",
    profilePicture: "/photos/persons/person-11.jpg",
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Rachel",
    email: "Telly.Hoeger@billy.biz",
    profilePicture: "/photos/persons/person-12.jpg",
    class: "onlineNow",
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Victoria",
    email: "Sherwood@rosamond.me",
    profilePicture: "/photos/persons/person-13.jpg",
  },
  {
    id: 9,
    name: "Catherine",
    username: "Maria",
    email: "Chaim_McDermott@dana.io",
    profilePicture: "/photos/persons/person-14.jpg",
    class: "onlineNow",
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Theresa",
    email: "Rey.Padberg@karina.biz",
    profilePicture: "/photos/persons/person-15.jpg",
  },
  {
    id: 11,
    name: "Sharon Mattew",
    username: "Charlotte",
    email: "Rey.Padberg@karina.biz",
    profilePicture: "/photos/persons/person-16.jpg",
    class: "onlineNow",
  },
];

export const UsersPosts = [
  {
    userId: 3,
    id: 1,
    title: "to make a blinded choice to reject or provident to task",
    body: "Life is better with friends by your side.",
    image: "/photos/posts/post1.jpg",
    date: "5h-",
    like: "100",
    comment: "70",
  },
  {
    userId: 2,
    id: 2,
    title: "who is to be",
    body: "Exploring new horizons, one step at a time.",
    image: "/photos/posts/post2.jpg",
    date: "23m-",
    like: "480",
    comment: "112",
  },
  {
    userId: 1,
    id: 3,
    title: "Finding beauty.",
    body: "Finding beauty in the simplest of things, a true work of art.",
    image: "/photos/posts/post3.jpg",
    date: "11h-",
    like: "10",
    comment: "30",
  },

  {
    userId: 5,
    id: 4,
    title: "dreams and reality.",
    body: "Where dreams and reality intertwine, creating magic.",
    image: "/photos/posts/post4.jpg",
    date: "23h- ",
    like: "10",
    comment: "30",
  },
  {
    userId: 4,
    id: 5,
    title: "Capturing moments.",
    body: "Capturing moments that take your breath away.",
    image: "/photos/posts/post5.jpg",
    date: "2d- ",
    like: "560",
    comment: "200",
  },
  {
    userId: 2,
    id: 6,
    title: "Finding joy.",
    body: "Finding joy in the little things.",
    image: "/photos/posts/post6.jpg",
    date: "2m- ",
    like: "130",
    comment: "31",
  },
  {
    userId: 1,
    id: 7,
    title: "pictures tell the story.",
    body: "Let the pictures tell the story.",
    image: "/photos/posts/post7.jpg",
    date: "2d- ",
    like: "10",
    comment: "30",
  },
  {
    userId: 5,
    id: 8,
    title: "Nature's masterpiece.",
    body: "Nature's masterpiece, painted with vibrant hues.",
    image: "/photos/posts/post8.jpg",
    date: "3h- ",
    like: "780",
    comment: "412",
  },
  {
    userId: 3,
    id: 9,
    title: "Creating memories.",
    body: "Creating memories that will last a lifetime.",
    image: "/photos/posts/post9.jpg",
    date: "2m- ",
    like: "10",
    comment: "3",
  },
  {
    userId: 2,
    id: 10,
    title: "Every picture has a story.",
    body: "Every picture has a story to tell.",
    image: "/photos/posts/post10.jpg",
    date: "4h- ",
    like: "86",
    comment: "12",
  },
  {
    userId: 6,
    id: 11,
    title: "the magic of the moment.",
    body: "Embracing the magic of the present moment.",
    image: "/photos/posts/post11.jpg",
    date: "1d- ",
    like: "1000",
    comment: "340",
  },
  {
    userId: 1,
    id: 12,
    title: "Discovering the world.",
    body: "Discovering the world, one photo at a time.",
    image: "/photos/posts/post12.jpg",
    date: "1h- ",
    like: "760",
    comment: "500",
  },
  {
    userId: 2,
    id: 13,
    title: "Finding peace.",
    body: "Finding peace in nature's embrace.",
    image: "/photos/posts/post13.jpg",
    date: "10m- ",
    like: "10",
    comment: "30",
  },
  {
    userId: 4,
    id: 14,
    title: "Celebrating life.",
    body: "Celebrating life's precious moments.",
    image: "/photos/posts/post14.jpg",
    date: "1d- ",
    like: "48",
    comment: "7",
  },
  {
    userId: 6,
    id: 15,
    title: "Dream big.",
    body: "Dream big, explore more.",
    image: "/photos/posts/post15.jpg",
    date: "1d- ",
    like: "48",
    comment: "7",
  },
  {
    userId: 7,
    id: 16,
    title: "Capturing",
    body: "Capturing the essence of wanderlust",
    image: "/photos/posts/post16.jpg",
    date: "1d- ",
    like: "48",
    comment: "7",
  },
  {
    userId: 3,
    id: 17,
    title: "Chasing dreams.",
    body: "Chasing dreams and capturing memories.",
    image: "/photos/posts/post17.jpg",
    date: "1d- ",
    like: "48",
    comment: "7",
  },
  {
    userId: 7,
    id: 18,
    title: "Life is a canvas.",
    body: "Life is a canvas, make it a masterpiece.",
    image: "/photos/posts/post18.jpg",
    date: "1d- ",
    like: "48",
    comment: "7",
  },
  {
    userId: 3,
    id: 19,
    title: "Nature's masterpiece.",
    body: "Nature's masterpiece, painted with vibrant hues.",
    image: "/photos/posts/post19.jpg",
    date: "1d- ",
    like: "48",
    comment: "7",
  },
  {
    userId: 5,
    id: 20,
    title: "A glimpse into the world.",
    body: "A glimpse into a world of enchantment and wonder.",
    image: "/photos/posts/post20.jpg",
    date: "1d- ",
    like: "48",
    comment: "7",
  },
];